#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
# bspwmrc by marcosdly
# Check marcosdly/dotfiles on GitHub

# Dynamic muilt-monitor setup. Max of 2 monitors
# and assuming that the monitor in on HDMI1.
# 
# Run xrandr to list video outputs.
#
# There is a bug that when you plug the second
# monitor it takes the first workspaces indexes,
# so (in my case) the secondary monitor gets
# 1-3 keys and the primary gets 4-0 keys, even
# with the secondary monitor having the 8-10
# workspaces and the primary 1-7. The different
# sxhkd config files fixes that. 
xrandr | grep 'HDMI1 connected'
if [[ $? -eq 0 ]]; then
bspc monitor eDP1 -d 1 2 3 4 5 6 7
bspc monitor HDMI1 -d 8 9 10

# Set the config file for sxhkd and reload it
killall sxhkd ; sxhkd -c ${HOME}/.config/sxhkd/bspwm2m &
else
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI1 -r

# Set the config file for sxhkd and reload it
killall sxhkd ; sxhkd -c ${HOME}/.config/sxhkd/bspwm &
fi

bspc config border_width         2
bspc config window_gap           5

#bspc config focus_follows_pointer false 
#bspc config normal_border_color   ######
bspc config focused_border_color '#656467'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a gnome-calculator state=floating
bspc rule -a spotify desktop='^10' follow=on
bspc rule -a discord desktop='^9' follow=off

# Programs to run at start
xsetroot -cursor_name left_ptr &
${HOME}/.fehbg
${HOME}/.config/polybar/bspwm-moon.sh &
picom &
lxsession &
setxkbmap br &
xset -dpms s off &
${HOME}/battery-status.sh &
paplay --volume=45875 /usr/share/sounds/freedesktop/stereo/service-login.oga & # 70% volume
#xautolock -time 10 -locker "betterlockscreen -u /home/marcosdly/Documents/config-files-and-stuff/wallpapers/moon-01.jpg -l blur" -notify 60 -notifier "notify-send" -detectsleep &
#spotify-listener &
#disown # Required by polybar-spotify-module documentation
